server:
  port: 9401
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  application:
    name: serve-auth
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.103.184:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  # RabbitMQ 相关配置项
  rabbitmq:
    host: 192.168.103.184
    port: 5672
    username: wangxd
    password: wangxd
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: none
  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://127.0.0.1:3306/yu_tenant_1?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
  redis:
    database: 0
    port: 6379
    host: 192.168.103.184
    #password:
management:
  endpoints:
    web:
      exposure:
        include: "*"
