spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yu_alone?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  sql:
    init:
      username: root
      password: 123456
      schema-locations: classpath:alone-sql/schema.sql
      data-locations: classpath:alone-sql/data.sql
      mode: always  #embedded (default) 默认值, 对嵌入式DB初始化, 其他不初始化
