server:
  servlet:
    context-path: /api
  port: 1128
spring:
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      repositories:
        enabled: false
    jdbc:
      repositories:
        enabled: false
  jpa:
    open-in-view: false
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: none
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yu_tenant_platform?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
yu:
  jwt:

  multidb:
    enabled: true
    type: prop  #type：多数据源配置信息获取类型， db: 数据库中获取；feign: 微服务 feign获取；prop：配置文件获取
    tenants:
      1001:
        admins: admin,superadmin
        datasource:
          url: jdbc:mysql://127.0.0.1:3306/yu_tenant_1?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: 123456
      1002:
        admins: admin,superadmin
        datasource:
          url: jdbc:mysql://127.0.0.1:3306/yu_tenant_2?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: 123456
      1003:
        admins: admin,superadmin
        datasource:
          url: jdbc:mysql://127.0.0.1:3306/yu_tenant_3?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: 123456
logging:
  level:
    org:
      springframework:
        #security: DEBUG
        web: ERROR