logging:
  level:
    org.springframework.cloud.gateway: trace
server:
  port: 9201
spring:
  profiles:
    active: dev
  application:
    name: serve-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.103.184:8848
    gateway:
      routes: #配置路由路径
        # 认证：用户名密码认证
        - id: oauth2-auth-route
          uri: lb://serve-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            # - AddRequestParameter=client_id, webApp
        # 服务：系统管理
        - id: oauth2-api-route
          uri: lb://serve-system
          predicates:
            - Path=/api_sy/**
          filters:
            - StripPrefix=1
        # 服务：结算平台
        - id: balance-service
          uri: http://192.168.118.230:8080
          predicates:
            - Path=/api_ba/**
          filters:
            - StripPrefix=1
            - PrefixPath=/staffcard
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: 192.168.103.184
    password:
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"